version: '3.9'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - external-network

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - external-network
    environment:
      - DEFAULT_EMAIL=${NGINX_PROXY_DEFAULT_EMAIL}

  apprtc-server:
    image: piasy/apprtc-server
    container_name: apprtc-server
    networks:
      - external-network
    environment:
      - LETSENCRYPT_HOST=${NGINX_PROXY_LETSENCRYPT_HOST}
      - VIRTUAL_HOST=${APPRTC_VIRTUAL_HOST}
      - VIRTUAL_HOST=${APPRTC_VIRTUAL_PORT}

volumes:
  certs:
  vhost:
  html:
  acme:

networks:
  default:
    external: true
    name: external-network