version: '3.9'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=${NGINX_PROXY_DEFAULT_EMAIL}

  apprtc-server:
    image: piasy/apprtc-server
    container_name: apprtc-server
    ports:
      - '8080:8080'
      - '8089:8089'
      - '3478:3478'
      - '3033:3033'
      - '3478:3478/udp'
      - '59000-65000:59000-65000/udp'
    environment:
      - LETSENCRYPT_HOST=${NGINX_PROXY_LETSENCRYPT_HOST}
      - VIRTUAL_HOST=${APPRTC_VIRTUAL_HOST}
      - VIRTUAL_HOST=${APPRTC_VIRTUAL_PORT}

volumes:
  certs:
  vhost:
  html:
  acme:
